// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://accgettpdwlpnuvteuho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjY2dldHRwZHdscG51dnRldWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODI5NzAsImV4cCI6MjA1OTg1ODk3MH0.q8Vqzv3xQc6exYGx-sYtT8UUyFJajw8pnGttB91klBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);